 const categoriesData = {
    Relaxation: [
      "Spa & Wellness Centers",
      "Yoga Studios",
      "Meditation Centers",
      "Parks & Gardens",
      "Beaches",
      "Lakes & Rivers",
      "Picnic Areas",
      "Hot Springs",
    ],

    Accommodation: [
      "Hotels",
      "Resorts",
      "Motels",
      "Bed & Breakfast",
      "Inns",
      "Guest Houses",
      "Vacation Rentals",
      "Camping Sites",
    ],
    Dining: [
      "Traditional foods",
      "Restaurants",
      "Cafes & Coffee Shops",
      "Bakeries",
      "Bars & Pubs",
      "Food Trucks",
      "Fine Dining Restaurants",
      "Ethnic Cuisine Restaurants",
      "Fast Food Chains",
      "Sea food",
    ],
    Entertainment: [
      "Movie Theaters",
      "Concert Halls",
      "Live Music Venues",
      "Night Clubs",
      "Bowling Alleys",
      "Arcahdes",
      "Amusement Parks",
      "Casinos",
      "Golf Courses",
    ],
    Culture_and_Historicalsites: [
      "Museums",
      "Art Galleries",
      "Historic Landmarks",
      "Monuments",
      "Archaelogical Sites",
      "Cultural Sites",
      "Heritage Sites",
      "Religious plsces of interest",
    ],
    Shopping: [
      "Shopping Malls",
      "Boutiques",
      "Markets",
      "Antique Stores",
      "Souvenir Shops",
      "Department stores",
      "Outlet Stores",
      "Speciality Stores",
    ],
    Education_and_Learning: [
      "Libraries",
      "Bookstores",
      "Education Centers",
      "Art Schools",
      "Cooking Schools",
      "Language Schools",
      "Workshops & Classes",
      "Reserch Institution",
    ],
    Health_and_Fitness: [
      "Sport Clubs",
      "Swimming Pools",
      "Martial arts Studios",
      "Gym",
      "Dance Studio",
      "Rock Climbing Gyms",
      "Cycling Tracks",
      "Running Tracks",
      "Hospital",
    ],
    Services: [
      "Spar & massage centers",
      "Hair Salons",
      "Nail Salons",
      "Dry Cleaners",
      "Pet Groomers",
      "Car Washes",
      "Post Offices",
      "Banks and ATMS",
      "Medical Centers",
      "legal Services",
    ],
  };

  export default categoriesData;